name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    name: Test checkly-trigger
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
      - name: Run checkly-trigger
        uses: ./
        with:
          repository: 'jackton1/api'
          sha: ''
          run-location: ${{ secrets.RUN_LOCATION }}
          environment-name: ${{ secrets.ENVIRONMENT_NAME }}
          trigger-url: ${{ secrets.TRIGGER_URL }}
