name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test checkly-trigger
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-11, windows-2022]
        deployment: ["true", "false"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
      - name: Run checkly-trigger
        uses: ./
        with:
          deployment: ${{ matrix.deployment }}
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          run-location: ${{ secrets.RUN_LOCATION }}
          environment-name: ${{ secrets.ENVIRONMENT_NAME }}
          deployment-id: ${{ secrets.DEPLOYMENT_ID }}
          trigger-url: ${{ secrets.TRIGGER_URL }}
